### ISSUE TITLE
Publish on PyPI

### ISSUE THREAD

**Issue by kovidgoyal** [ebook-utils/css-parser#1]
This issue is to track progress with publishing css-parser on pypi. Once all maintainers feel we are ready to make a release, I propose bumping the version number and releasing on PyPI. Unless someone else wants to do it, I will be happy to make the release/publish under my account on PyPI.

**Comment by kevinhendricks** [comment]
I think the current state fixes all known issues we had with cssutils.  That said, there are other more rarely used at-rules such as @supports that I have seen in real ebooks that we should eventually add support for. 

So I am okay with bumping the version number (I did that once but even resetting the numbering wouldn't hurt), and starting the process to release/publish css-parser under your account on PyPi.

Sigil is going to embed this css-parser into our plugin library for the next couple releases so timing of when to publish on PyPi is not critical to us.

**Comment by wrCisco** [comment]
I forgot to write the inline documentation of the two new prefs in the serializer (I can do it right now), and we can also add Kovid's [patch](https://bitbucket.org/cthedot/cssutils/issues/46/serialization-of-multiline-comments-broken) to avoid shifting of multiline comments inside rules's declarations (I'd just un-tab of one level the 'out.append(separator)' line, out of the else block).

Other than that I'm OK with the publication.

**Comment by kevinhendricks** [comment]
Sounds good to me.  Once you get those changes in place, please let everyone know, and Sigil will pull the first version to include into its next release so Sigil can work on fixing the css reformatting issue and close it.

**Comment by wrCisco** [comment]
Ok, I added both.

**Comment by kovidgoyal** [comment]
I have updated setup.py, to change project name, author, urls etc. Please review and let me know if you are all ok with it. Then I will go ahead and bump the version and publish.

**Comment by wrCisco** [comment]
OK for me.

**Comment by kevinhendricks** [comment]
Looks good to me too.

**Comment by dougmassay** [comment]
Not a big deal at all in terms of publishing, but I noticed the status badge for AppVeyor in the README is showing as "unknown," even though the last checks show everything passed.

**Comment by kovidgoyal** [comment]
that's just an artifact of github caching, it will hopefully get updated eventually

**Comment by kovidgoyal** [comment]
published at: https://pypi.org/project/css-parser/

I dont use pypi myself, so if there are any issues with the upload, let me know and I will fix them.

**Comment by wrCisco** [comment]
I just tried it, installation went smoothly. The badges in the project description aren't displayed correctly, though (two links attached together, it seems).

**Comment by kovidgoyal** [comment]
Feel free to correct the links.

**Comment by dougmassay** [comment]
I think PyPI's a little pickier about the Markdown that works in its descriptions. I'd probably just strip the badges out of the readme/description before publishing next time.

**Comment by wrCisco** [comment]
I just added long_description_content_type='text/markdown' in setup.py (I'm not sure that solves the issue, but I think it's harmless to try).

**Comment by kovidgoyal** [comment]
Good find, as far as I can tell, it *should* fix it. We will know after the next release.
