### ISSUE TITLE
Please add support for Python 3.10

### ISSUE THREAD

**Issue by sten0** [ebook-utils/css-parser#10]
Hi @kovidgoyal,

Debian has begun its Python 3.9 to 3.10 migration; however, css-parser is unfortunately not ready for 3.10.  More information can be found at [Bug #1001419](https://bugs.debian.org/1001419) _python-css-parser: (autopkgtest) needs update for python3.10: Right exception, wrong message: got 'can't set attribute 'literalname'' instead of 'can't set attribute'_.  I am of course happy to test a prerelease or to cherry pick the fix.

Kind regards,
Nicholas

**Comment by kevinhendricks** [comment]
See https://github.com/ebook-utils/css-parser/commit/6b5e22217d69fbe4afe17f614af663af66de284f

**Comment by sten0** [comment]
Kevin Hendricks ***@***.***> writes:

> See https://github.com/ebook-utils/css-parser/commit/6b5e22217d69fbe4afe17f614af663af66de284f
>

Thank you, yes, this commit appears to address the issue.  Sorry for my
laziness/exhaustion; I had assumed that a stable css-parser release
would have been made in November or December so that PyPI users could
benefit from Python 3.10 support.  Cherry picking this commit now for
the Debian package.

Would you like me to test HEAD as well, or is it not ready yet?

**Comment by kovidgoyal** [comment]
I just released 1.0.7 use that.

**Comment by sten0** [comment]
Kovid Goyal ***@***.***> writes:

> I just released 1.0.7 use that.

Thanks :-)  Updating to 1.0.7 (from 1.0.6 plus cherry picked commits) now!
