### ISSUE TITLE
please update fix misleading copyright in release tarball (PyPI)

### ISSUE THREAD

**Issue by sten0** [ebook-utils/css-parser#4]
Hi,

Thank you for maintaining css-parser.  I recently packaged it for Debian (new dep for Calibre, thank you to anyone here who also works on it!), and an ftp-master asked me to pursue license clarification upstream.  Here is the copyright analysis for v1.0.4 from PyPI: https://sources.debian.org/src/python-css-parser/1.0.4-1/debian/copyright/

In particular PKG-INFO, setup.py, and src/css_parser.egg-info/PKG-INFO should be updated to assert LGPL-3+, and COPYING.LESSER should be included in the release tarball.

From what I gather the GPL-3+ bits are primarily relevant to the github project and release process, and not to PyPI releases of css-parser; however, the fact that css_parser/version.py is GPL-3+ indicates that this might not be the case...  The easiest thing for disambiguation would be to relicense css_parser/version.py as LGPL-3+ in addition to addressing the issues in the paragraph above.

Cheers!
Nicholas

**Comment by kovidgoyal** [comment]
PKG-INFO is a generated file, so nothing that can be done there. The
other requested changes have been made.
