### ISSUE TITLE
please make tests discoverable to unittest and pytest

### ISSUE THREAD

**Issue by sten0** [ebook-utils/css-parser#7]
Hi,

Thank you again for maintaining css-parser :-)  It would be really nice if tests were discoverable to unittest (eg: `python3 -m unittest discover -v`) and runable with pytest.  This will let Debian CI infrastructure test correct functionality of css-parser as-installed, rather than from the source repository, and I'd like to do everything I can to ensure that our users experience your software as you intend it: well-tested on the platform it is shipped with.  We have three levels of CI, by the way (build-time-self-tests+reproducibility tests, DebCI aka "autopkgtests", and the Gitlab CI--a Travis equivalent).

Regards,
Nicholas

**Comment by kovidgoyal** [comment]
Tests are runnable using the standard

./setup.py test

**Comment by kovidgoyal** [comment]
And in fact they wori with python -m unittest discover as well.

**Comment by sten0** [comment]
> And in fact they wori with python -m unittest discover as well.


Thank you for confirming!  I was worried that `run_tests.py` was the
only supported interface.  After some digging I was able to confirm that
the cause of "missing tests" was that for some reason the Debian tools
weren't copying `css_parser_tests` into the build-dir (I've never seen
this case in a Python package before).  Eventually I hope to discover
why `css_parser_tests` triggers a case different than any other I've seen.
Until then, I'm confident in the workaround :-)

Best,
Nicholas
